app:
  domain:    .domain
  secret:    'dd9594b9daa9ac2c0007ca9bd91a48f3429b930ad956730e140723d942e62e27c4e9bbe6eaa84dfc6106fba0f1bafaeb627ed0cda96906844981246dc4dc2a3b'
  from:      'zg_mail@test.ru'
  host:      'localhost:3000'

redis_user_connector:
  url: 'redis://localhost:6379/3'

session_store:
  db:             4
  key_prefix:     'session:'
  host:           'localhost'
  port:           6379

profile:
  url:          'http://localhost:3000'
  sign_in_url:  'http://localhost:3000/users/sign_in'
  sign_up_url:  'http://localhost:3000/users/sign_up'
  sign_out_url: 'http://localhost:3000/users/sign_out'

